import type { Copy, Lang } from "@/lib/types";

export const copy: Record<Lang, Copy> = {
  en: {
    eyebrow: "Lead studio · Munich",
    subtitle:
      "Pick a niche, draft a Meta lead offer, preview the form a customer actually sees, and watch inquiries land in the CRM.",
    stepNiche: "Niche",
    stepOffer: "Offer",
    stepPreview: "Preview",
    stepCrm: "CRM",
    step1Title: "Choose a business niche",
    step1Hint: "The offer, the form, and new leads follow this choice.",
    step2Title: "AI Lead & Offer Generator",
    step2Hint: "Hooks and the question order for a Meta lead form.",
    step3Title: "Instant preview",
    step3Hint: "What the customer sees before they send a phone number.",
    step4Title: "CRM Lead Flow",
    step4Hint: "Test inquiries. Click a status to move it forward.",
    generate: "Generate a new offer with AI",
    generating: "Composing a new offer…",
    simulate: "Simulate incoming lead",
    liveOn: "Live intake on",
    liveOff: "Live intake off",
    headlines: "Hooks",
    structure: "Lead form structure",
    german: "German",
    english: "English",
    variant: "Variant",
    emptyOfferTitle: "Waiting for a niche",
    emptyOffer: "Select a card above. The generator will draft headlines and the question order for that market.",
    emptyPreview: "The customer view appears after you pick a niche.",
    previewKicker: "Meta · Lead form",
    sponsored: "Sponsored",
    name: "Full name",
    phone: "Phone",
    namePh: "Lena Hoffmann",
    phonePh: "+49 171 000 0000",
    selectPh: "Choose one",
    required: "Name and phone are required.",
    captured: "Lead sent to CRM",
    privacy: "Preview only. Submit drops the lead into the dashboard below.",
    contact: "Contact",
    filterAll: "All",
    status: {
      new: "New",
      qualified: "Qualified",
      in_progress: "In progress",
    },
    statusHint: "Click a status to advance it",
    columns: {
      name: "Name",
      phone: "Phone",
      niche: "Niche",
      status: "Status",
      time: "Time",
    },
    stats: {
      total: "In flow",
      fresh: "New",
      qualified: "Qualified",
      working: "In progress",
    },
    incoming: "Incoming lead",
    selected: "Selected",
    noLeads: "No leads in this view.",
    footer: "Demo workspace. Nothing leaves this browser.",
    drafting: "AI · drafting",
  },
  de: {
    eyebrow: "Lead-Studio · München",
    subtitle:
      "Nische wählen, Meta-Angebot entwerfen, die Form sehen, die der Kunde wirklich ausfüllt — und Anfragen im CRM landen lassen.",
    stepNiche: "Nische",
    stepOffer: "Angebot",
    stepPreview: "Vorschau",
    stepCrm: "CRM",
    step1Title: "Geschäftsniche wählen",
    step1Hint: "Angebot, Formular und neue Leads folgen dieser Wahl.",
    step2Title: "AI Lead & Offer Generator",
    step2Hint: "Hooks und die Fragenreihenfolge für eine Meta-Lead-Form.",
    step3Title: "Live-Vorschau",
    step3Hint: "So sieht der Kunde die Form, bevor er seine Nummer schickt.",
    step4Title: "CRM Lead Flow",
    step4Hint: "Testanfragen. Status antippen, um ihn weiterzuschieben.",
    generate: "Neues Angebot mit KI erzeugen",
    generating: "Neues Angebot wird geschrieben…",
    simulate: "Eingehenden Lead simulieren",
    liveOn: "Live-Eingang an",
    liveOff: "Live-Eingang aus",
    headlines: "Hooks",
    structure: "Struktur der Lead-Form",
    german: "Deutsch",
    english: "Englisch",
    variant: "Variante",
    emptyOfferTitle: "Wartet auf eine Nische",
    emptyOffer: "Karte oben wählen. Der Generator schreibt Hooks und die Fragenreihenfolge für diesen Markt.",
    emptyPreview: "Die Kundensicht erscheint, sobald eine Nische gewählt ist.",
    previewKicker: "Meta · Lead-Form",
    sponsored: "Gesponsert",
    name: "Name",
    phone: "Telefon",
    namePh: "Lena Hoffmann",
    phonePh: "+49 171 000 0000",
    selectPh: "Bitte wählen",
    required: "Name und Telefon werden benötigt.",
    captured: "Lead ist im CRM",
    privacy: "Nur eine Vorschau. Absenden legt den Lead ins Dashboard.",
    contact: "Kontakt",
    filterAll: "Alle",
    status: {
      new: "Neu",
      qualified: "Qualifiziert",
      in_progress: "In Bearbeitung",
    },
    statusHint: "Status antippen, um ihn weiterzuschieben",
    columns: {
      name: "Name",
      phone: "Telefon",
      niche: "Nische",
      status: "Status",
      time: "Zeit",
    },
    stats: {
      total: "Im Flow",
      fresh: "Neu",
      qualified: "Qualifiziert",
      working: "In Bearbeitung",
    },
    incoming: "Neuer Lead",
    selected: "Gewählt",
    noLeads: "Keine Leads in dieser Ansicht.",
    footer: "Demo. Es verlässt nichts diesen Browser.",
    drafting: "KI · schreibt",
  },
  ru: {
    eyebrow: "Студия лидогенерации · Мюнхен",
    subtitle:
      "Выберите нишу, соберите оффер для Meta, посмотрите форму глазами клиента и примите заявки в CRM.",
    stepNiche: "Ниша",
    stepOffer: "Оффер",
    stepPreview: "Превью",
    stepCrm: "CRM",
    step1Title: "Выбор бизнес-ниши",
    step1Hint: "Оффер, форма и новые лиды следуют за этим выбором.",
    step2Title: "AI Lead & Offer Generator",
    step2Hint: "Заголовки и порядок вопросов для лид-формы Meta.",
    step3Title: "Живое превью",
    step3Hint: "Так клиент видит форму до того, как оставит телефон.",
    step4Title: "CRM Lead Flow",
    step4Hint: "Тестовые заявки. Нажмите статус, чтобы сдвинуть его дальше.",
    generate: "Сгенерировать новый оффер с ИИ",
    generating: "Собираем новый оффер…",
    simulate: "Симулировать входящий лид",
    liveOn: "Живой поток включён",
    liveOff: "Живой поток выключен",
    headlines: "Заголовки",
    structure: "Структура лид-формы",
    german: "Немецкий",
    english: "Английский",
    variant: "Вариант",
    emptyOfferTitle: "Ждём нишу",
    emptyOffer: "Выберите карточку выше. Генератор соберёт заголовки и порядок вопросов для этого рынка.",
    emptyPreview: "Вид для клиента появится после выбора ниши.",
    previewKicker: "Meta · Лид-форма",
    sponsored: "Реклама",
    name: "Имя",
    phone: "Телефон",
    namePh: "Лена Хоффманн",
    phonePh: "+49 171 000 0000",
    selectPh: "Выберите",
    required: "Нужны имя и телефон.",
    captured: "Лид отправлен в CRM",
    privacy: "Только превью. Отправка кладёт лид в дашборд ниже.",
    contact: "Контакт",
    filterAll: "Все",
    status: {
      new: "Новый",
      qualified: "Квалифицирован",
      in_progress: "В работе",
    },
    statusHint: "Нажмите статус, чтобы перевести его дальше",
    columns: {
      name: "Имя",
      phone: "Телефон",
      niche: "Ниша",
      status: "Статус",
      time: "Время",
    },
    stats: {
      total: "В потоке",
      fresh: "Новые",
      qualified: "Квалифицированы",
      working: "В работе",
    },
    incoming: "Входящий лид",
    selected: "Выбрано",
    noLeads: "В этом виде заявок нет.",
    footer: "Демо. Данные не покидают браузер.",
    drafting: "ИИ · пишет",
  },
};
